resolver: lts-16.8
compiler-check: match-exact
compiler: ghc-8.10.1

packages:
- .

extra-deps: 
- 'hakyll-images-0.4.4'
- github: jaspervdj/hakyll
  commit: 7873e570afb3b51b2382e158bfd45e7ba6889981

allow-newer: true