resolver: lts-17.9 # GHC 8.10.3

compiler: ghc-8.10.4

packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
# (e.g., acme-missiles-0.3)
extra-deps: 
- pandoc-2.13
- hslua-module-path-0.1.0.1
- 'hakyll-images-1.0.1'
- git: https://github.com/LaurentRDC/hakyll.git
  commit: 978820568a8483e6c6d04afe39aee8f7cac94465