name: Render site

on:
  push:
    branches: [master]
  schedule:
    # Build the website twice a week, to keep it up-to-date
    # and keep the cache warm.
    # See https://crontab.guru/#0_5_*_*_0,4
    - cron: '0 3 * * 1,5'

jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell toolchain
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/cache@v1
      name: Cache Haskell build artifacts
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

    - name: Build site compiler
      run: |
        stack install
        
    - name: Download Bulma CSS
      env:
        bulma-version: 0.9.1
      run: |
        wget -c https://github.com/jgthms/bulma/releases/download/${{ env.bulma-version }}/bulma-${{ env.bulma-version }}.zip 
        unzip bulma-${{ env.bulma-version }}.zip -d sass

    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: sass/siwick-style.scss
        destination: css/siwick-style.css
        
    - name: Build website
      run: |
        stack exec -- siwick-website clean
        stack exec -- siwick-website build
    
    - name: Check links
      run: |
        stack exec -- siwick-website check --internal-links
    
    - name: Deployment
      env:
        SERVER: ${{ secrets.CPM_SERVER }}
        PRIVATE_KEY: ${{ secrets.CPM_PRIVATE_SSH_KEY }}
      run: |
        printf "%s" "$PRIVATE_KEY" > identity-file
        printf "%s" "put -r _rendered /WWW/decotret/siwicklab" > deploy-script
        sftp -b deploy-script -i identity-file decotret@$SERVER

