name: Render site

on:
  push:
    branches: [master]
  schedule:
    # Build the website twice a week, to keep it up-to-date
    # and keep the cache warm.
    # See https://crontab.guru/#0_5_*_*_0,4
    - cron: '0 3 * * 1,5'

jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell toolchain
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/cache@v1
      name: Cache Haskell build artifacts
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

    - name: Build site compiler
      run: |
        stack install
        
    - name: Download Bulma CSS
      env:
        bulma-version: 0.9.1
      run: |
        wget -c https://github.com/jgthms/bulma/releases/download/${{ env.bulma-version }}/bulma-${{ env.bulma-version }}.zip 
        unzip bulma-${{ env.bulma-version }}.zip -d sass

    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: sass/siwick-style.scss
        destination: css/siwick-style.css
        
    - name: Build website
      run: |
        stack exec -- siwick-website clean
        stack exec -- siwick-website build
    
    - name: Check links
      run: |
        stack exec -- siwick-website check --internal-links

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'decotret'
        server: ${{ secrets.CPM_SERVER }}
        ssh_private_key: ${{ secrets.CPM_PRIVATE_SSH_KEY }}
        local_path: './_rendered/*'
        remote_path: 'website'
        args: '-o ConnectTimeout=120'

    - name: Sync to WWW
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'decotret@${{ secrets.CPM_SERVER }}'
        privateKey: ${{ secrets.CPM_PRIVATE_SSH_KEY }}
        command: |
          rsync -va --delete 'website/' /WWW/decotret/siwicklab
          rm -rf website

